In [2]:
import numpy as np

## 1. Nhập mảng 1 chiều, 2 chiều vào numpy

In [3]:
list_1_dimensional = [1,2,3,4]

In [4]:
np.array(list_1_dimensional)

array([1, 2, 3, 4])

In [5]:
list_2_dimensional = [[1,2,3],[4,5,6]]

In [6]:
np.array(list_2_dimensional)

array([[1, 2, 3],
       [4, 5, 6]])

## 2. Tự động tạo mảng

### Tự động tạo mảng theo số thứ tự

In [7]:
np.arange(0, 10) #0 to n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.array((np.arange(0, 10), np.arange(0, 10)))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Tự động tạo mảng 0, 1

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Tự động tạo mảng cách đều trong khoảng từ a->b
Ví dụ là từ 0 đến 5 có 6 phần tử thì sẽ có mảng là [0,1,2,3,4,5]

In [19]:
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [20]:
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

### Tạo ra ma trận định thức

In [22]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Tạo ra ma trận ngẫu nhiên
Tạo ra ma trận từ 0 đến 1

In [24]:
np.random.rand(10)

array([0.43202043, 0.21683416, 0.43771661, 0.59535851, 0.83142387,
       0.78996397, 0.93363654, 0.27806371, 0.98757492, 0.91505979])

In [29]:
np.random.rand(3, 3)

array([[0.55129602, 0.64352968, 0.29697446],
       [0.92042771, 0.82306782, 0.85504358],
       [0.81813314, 0.1502765 , 0.5425486 ]])

Tạo ra ma trận ngẫu nhiên dạng phân phối chuẩn có mean là 0 và stdev là -1

In [31]:
np.random.randn(10)

array([ 0.61138262, -0.55997631, -1.14248888, -0.53342316,  0.82058444,
       -0.83725673, -0.53224141, -1.61694673,  1.01191797, -0.93354043])

Tạo ra ma trận ngẫu nhiên từ a đến b

In [32]:
np.random.randint(1, 10, 20)

array([8, 4, 7, 7, 1, 5, 5, 3, 8, 3, 4, 7, 2, 1, 2, 4, 5, 9, 5, 3])

## 3. Hàm liên quan tới việc thay đổi hình dạng mảng

In [46]:
array_1 = np.arange(20)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
array_1.shape

(20,)

In [48]:
array_1 = array_1.reshape(5,4) #Không thể thay đổi cỡ mà to hơn kích thước mảng gốc được

In [49]:
array_1.shape

(5, 4)

## 4. Hàm liên quan đến max-min trong mảng, ma trận

In [59]:
list_test_4 = np.array([[6,5,3],[4,2,1]])
list_test_4

array([[6, 5, 3],
       [4, 2, 1]])

In [60]:
list_test_4.max()

6

In [61]:
list_test_4.min()

1

In [62]:
list_test_4.argmax()

0

In [63]:
list_test_4.argmin()

5

## 5. Check xem ma trận có kiểu gì

In [65]:
list_test_4.dtype

dtype('int32')

## 6. BONUS: Random số trong numpy

In [66]:
from numpy.random import randint
randint(2, 10)

5